name: End-to-end tests
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: false
          publish-summary: true
          component: false
          working-directory: e2e-testing
